package tests;

import java.util.*;
import processj.runtime.*;

/**
 * File Generated by the ProcessJ JVM Compiler.
 * Package name `hello'.
 * Code generation for `hello'.
 * Target class `hello'.
 * Java code version `1.8.0_66'.
 *
 * @author ProcessJ Group
 * @since 1.2
 */
public class hello {
    public static void _method$hello() {
        JVM.std.io.println("Hello! from method 'hello'");
    }

    public static void _method$world() {
        JVM.std.io.println("World! from method 'world'");
    }

    public static class _proc$main extends PJProcess {
        public String[] _pd$args1;

        public _proc$main(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            JVM.std.io.println("Hello World!");
            _method$hello();
            _method$world();
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
        Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new hello._proc$main(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}
