import java.util.*;
import processj.runtime.*;
import std.*;


/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'array.pj'.
 * Target class 'array'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas
 * @since 1.2
 *
 */
public class array {
    // Temporary dirty fix for unreachable code due to infinite loop
    public static boolean isTrue() { return true; }

    public static class _proc$main$arT extends PJProcess {
        protected String[] _pd$args1;

        protected String _ld$str1;
        protected int[] _ld$x2;
        protected int[][] _ld$a3;
        protected int[][][] _ld$array4;
        protected int[][][] _ld$test5;

        public _proc$main$arT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            _ld$str1 = "Benjamin Cisneros";
            io.println(_ld$str1.length());
            _ld$x2 = new int[]{ 1,2,3,4 };
            io.println("x size " + _ld$x2.length);
            _ld$a3 = new int[][]{  { 1, 2 } , { 3, 5 }  };
            _ld$array4 = new int[][][]{  {  { 10, 20, 30 } ,  { 50, 60, 70 } ,  { 80, 90, 100 } ,  { 110, 120, 130 }  } , {  { 15, 25, 35 } ,  { 22, 44, 66 } ,  { 33, 55, 77 } ,  { 78, 57, 76 }  }  };
            io.println("array[0] size " + _ld$array4[0].length);
            io.println("array[0][0] size " + _ld$array4[0][0].length);
            _ld$test5 = new int[][][]{  {  { 1, 2, 3 } ,  { 2, 3, 4 }  } , {  { 4, 5, 6, 9 } ,  { 1 } ,  { 2, 3 }  }  };
            io.println("test[0] size " + _ld$test5[0].length);
            io.println("test[0][0] size " + _ld$test5[0][0].length);
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new array._proc$main$arT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}