import java.util.*;
import processj.runtime.*;
import std.io;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'commstime'.
 * Target class 'commstime'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group
 * @since 1.2
 *
 */
public class commstime {
    // TODO: This a temporary fix for unreachable code due to
    // infinite loop
    public static boolean isTrue() { return true; }

    public static class _proc$prefix$J$chanreadJ$chanwriteJ extends PJProcess {
        protected long _pd$n1;
        protected PJOne2OneChannel<Long> _pd$in2;
        protected PJOne2OneChannel<Long> _pd$out3;

        protected long _ld$l1;

        public _proc$prefix$J$chanreadJ$chanwriteJ(long _pd$n1, PJOne2OneChannel<Long> _pd$in2, PJOne2OneChannel<Long> _pd$out3) {
            this._pd$n1 = _pd$n1;
            this._pd$in2 = _pd$in2;
            this._pd$out3 = _pd$out3;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                case 2: resume(2); break;
                case 3: resume(3); break;
                case 4: resume(4); break;
                default: break;
            }

            _pd$out3.write(this, _pd$n1);
            this.runLabel = 1;
            yield();
            label(1);

            _ld$l1 = 0;
            while (_ld$l1 < 5) {
                if (!_pd$in2.isReadyToRead(this)) {
                    this.runLabel = 2;
                    yield();
                }

                label(2);
                _ld$l1 = _pd$in2.read(this);
                this.runLabel = 3;
                yield();

                label(3);

                _pd$out3.write(this, _ld$l1);
                this.runLabel = 4;
                yield();
                label(4);

            }
            terminate();
        }
    }


    public static class _proc$succ$chanreadJ$chanwriteJ extends PJProcess {
        protected PJOne2OneChannel<Long> _pd$in1;
        protected PJOne2OneChannel<Long> _pd$out2;

        protected long _ld$l1;

        public _proc$succ$chanreadJ$chanwriteJ(PJOne2OneChannel<Long> _pd$in1, PJOne2OneChannel<Long> _pd$out2) {
            this._pd$in1 = _pd$in1;
            this._pd$out2 = _pd$out2;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                case 2: resume(2); break;
                case 3: resume(3); break;
                default: break;
            }

            _ld$l1 = 0;
            while (_ld$l1 < 5) {
                if (!_pd$in1.isReadyToRead(this)) {
                    this.runLabel = 1;
                    yield();
                }

                label(1);
                _ld$l1 = _pd$in1.read(this);
                this.runLabel = 2;
                yield();

                label(2);

                _pd$out2.write(this, _ld$l1 + 1);
                this.runLabel = 3;
                yield();
                label(3);

            }
            terminate();
        }
    }


    public static class _proc$delta$chanreadJ$chanwriteJ$chanwriteJ extends PJProcess {
        protected PJOne2OneChannel<Long> _pd$in1;
        protected PJOne2OneChannel<Long> _pd$out12;
        protected PJOne2OneChannel<Long> _pd$out23;

        protected long _ld$l1;

        public _proc$delta$chanreadJ$chanwriteJ$chanwriteJ(PJOne2OneChannel<Long> _pd$in1, PJOne2OneChannel<Long> _pd$out12, PJOne2OneChannel<Long> _pd$out23) {
            this._pd$in1 = _pd$in1;
            this._pd$out12 = _pd$out12;
            this._pd$out23 = _pd$out23;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                case 2: resume(2); break;
                case 3: resume(3); break;
                default: break;
            }

            _ld$l1 = 0;
            while (_ld$l1 < 5) {
                if (!_pd$in1.isReadyToRead(this)) {
                    this.runLabel = 1;
                    yield();
                }

                label(1);
                _ld$l1 = _pd$in1.read(this);
                this.runLabel = 2;
                yield();

                label(2);

                final PJPar _ld$par1 = new PJPar(2, this);

                new PJProcess() {
                    @Override
                    public synchronized void run() {
                        switch (this.runLabel) {
                            case 0: break;
                            case 1: resume(1); break;
                            default: break;
                        }

                        _pd$out12.write(this, _ld$l1);
                        this.runLabel = 1;
                        yield();
                        label(1);

                        terminate();
                    }

                    @Override
                    public void finalize() {
                        _ld$par1.decrement();
                    }
                }.schedule();

                new PJProcess() {
                    @Override
                    public synchronized void run() {
                        switch (this.runLabel) {
                            case 0: break;
                            case 1: resume(1); break;
                            default: break;
                        }

                        _pd$out23.write(this, _ld$l1);
                        this.runLabel = 1;
                        yield();
                        label(1);

                        terminate();
                    }

                    @Override
                    public void finalize() {
                        _ld$par1.decrement();
                    }
                }.schedule();

                setNotReady();
                this.runLabel = 3;
                yield();
                label(3);

            }
            terminate();
        }
    }


    public static class _proc$consume$chanreadJ extends PJProcess {
        protected PJOne2OneChannel<Long> _pd$in1;

        protected long _ld$l1;

        public _proc$consume$chanreadJ(PJOne2OneChannel<Long> _pd$in1) {
            this._pd$in1 = _pd$in1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                case 2: resume(2); break;
                default: break;
            }

            _ld$l1 = 0;
            while (_ld$l1 < 5) {
                if (!_pd$in1.isReadyToRead(this)) {
                    this.runLabel = 1;
                    yield();
                }

                label(1);
                _ld$l1 = _pd$in1.read(this);
                this.runLabel = 2;
                yield();

                label(2);

                io.println(_ld$l1);
            }
            terminate();
        }
    }


    public static class _proc$main$arrT extends PJProcess {
        protected String[] _pd$args1;

        protected PJOne2OneChannel<Long> _ld$a1;
        protected PJOne2OneChannel<Long> _ld$b2;
        protected PJOne2OneChannel<Long> _ld$c3;
        protected PJOne2OneChannel<Long> _ld$d4;

        public _proc$main$arrT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                default: break;
            }

            _ld$a1 = new PJOne2OneChannel<Long>();
            _ld$b2 = new PJOne2OneChannel<Long>();
            _ld$c3 = new PJOne2OneChannel<Long>();
            _ld$d4 = new PJOne2OneChannel<Long>();
            final PJPar _ld$par1 = new PJPar(4, this);

            (new commstime._proc$delta$chanreadJ$chanwriteJ$chanwriteJ(_ld$d4, _ld$a1, _ld$b2) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new commstime._proc$succ$chanreadJ$chanwriteJ(_ld$b2, _ld$c3) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new commstime._proc$prefix$J$chanreadJ$chanwriteJ(0, _ld$c3, _ld$d4) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new commstime._proc$consume$chanreadJ(_ld$a1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            setNotReady();
            this.runLabel = 1;
            yield();
            label(1);

            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new commstime._proc$main$arrT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}