import java.util.*;
import processj.runtime.*;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'Demo2'.
 * Target class 'Demo2'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group
 * @since 1.2
 *
 */
public class Demo2 {
    public static class _proc$main extends PJProcess {
        private String[] _pd$args1;

        private PJPar _ld$par1 = new PJPar(0, this);
        private PJPar _ld$par2 = new PJPar(0, this);

        public _proc$main(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new Demo2._proc$main(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}