import java.util.*;
import processj.runtime.*;
import std.io;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'Demo'.
 * Target class 'Demo'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group
 * @since 1.2
 *
 */
public class Demo {
    static class _rec$K implements PJRecord {
        public int a;
        public A aa;
        public int z;

        public _rec$K(int a, A aa, int z) {
            this.a = a;
            this.aa = aa;
            this.z = z;
        }

        public String getName() { return getPJRecordName(); }
    }

    static class _rec$T implements PJRecord {
        public int a;
        public A aa;

        public _rec$T(int a, A aa) {
            this.a = a;
            this.aa = aa;
        }

        public String getName() { return getPJRecordName(); }
    }

    static class _rec$X implements PJRecord {
        public int a;
        public A aa;
        public int p;

        public _rec$X(int a, A aa, int p) {
            this.a = a;
            this.aa = aa;
            this.p = p;
        }

        public String getName() { return getPJRecordName(); }
    }

    static class _rec$P implements PJRecord {
        public int a;
        public A aa;
        public int z;
        public int p;
        public int x;
        public int y;

        public _rec$P(int a, A aa, int z, int p, int x, int y) {
            this.a = a;
            this.aa = aa;
            this.z = z;
            this.p = p;
            this.x = x;
            this.y = y;
        }

        public String getName() { return getPJRecordName(); }
    }

    static class _rec$A implements PJRecord {
        public String c;

        public _rec$A(String c) {
            this.c = c;
        }

        public String getName() { return getPJRecordName(); }
    }

    public static class _proc$writer$cwI extends PJProcess {
        protected PJOne2OneChannel<Integer> _pd$out1;

        public _proc$writer$cwI(PJOne2OneChannel<Integer> _pd$out1) {
            this._pd$out1 = _pd$out1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                default: break;
            }

            _pd$out1.write(this, 42);
            this.runLabel = 1;
            yield();
            label(1);

            terminate();
        }
    }


    public static class _proc$reader$crI extends PJProcess {
        protected PJOne2OneChannel<Integer> _pd$in1;

        protected int _ld$value1;

        public _proc$reader$crI(PJOne2OneChannel<Integer> _pd$in1) {
            this._pd$in1 = _pd$in1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                case 2: resume(2); break;
                default: break;
            }

            if (!_pd$in1.isReadyToRead(this)) {
                this.runLabel = 1;
                yield();
            }

            label(1);
            _ld$value1 = _pd$in1.read(this);
            this.runLabel = 2;
            yield();

            label(2);

            io.println("The value is " + _ld$value1);
            terminate();
        }
    }


    public static class _proc$main$arT extends PJProcess {
        protected String[] _pd$args1;

        protected PJOne2OneChannel<Integer> _ld$c1;
        protected int _ld$a2;

        public _proc$main$arT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                default: break;
            }

            _ld$c1 = new PJOne2OneChannel<Integer>();
            _ld$a2 = 2;
            final PJPar _ld$par1 = new PJPar(2, this);

            (new Demo._proc$writer$cwI(_ld$c1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new Demo._proc$reader$crI(_ld$c1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            setNotReady();
            this.runLabel = 1;
            yield();
            label(1);

            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new Demo._proc$main$arT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}