import java.util.*;
import processj.runtime.*;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'localDecl.pj'.
 * Target class 'localDecl'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas
 * @since 1.2
 *
 */
public class localDecl {
    // Temporary dirty fix for unreachable code due to infinite loop
    public static boolean isTrue() { return true; }

    public static void _method$foo0() {
        boolean _ld$tempLoop01;
        boolean _ld$a2;

        _ld$tempLoop01 = true;
        _ld$a2 = true;
        while (_ld$tempLoop01) {
        }
    }
}