import java.util.*;
import processj.runtime.*;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'Pkg'.
 * Code generation for 'Main'.
 * Target class 'Main'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group
 * @since 1.2
 *
 */
public class Main {
    public static class _proc$main$arT extends PJProcess {
        protected String[] _pd$args1;

        protected a _ld$ben1;

        public _proc$main$arT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new Main._proc$main$arT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}