import java.util.*;
import processj.runtime.*;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'santatest.pj'.
 * Target class 'santatest'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas
 * @since 1.2
 *
 */
public class santatest {
    // Temporary dirty fix for unreachable code due to infinite loop
    public static boolean isTrue() { return true; }

    protected static class Santa_msg {
        protected static class reindeer_ready extends PJProtocolCase {
            public reindeer_ready() {
                this.tag = "reindeer_ready";
            }
        }

        protected static class harness extends PJProtocolCase {
            public int id;

            public harness(int id) {
                this.id = id;
                this.tag = "harness";
            }
        }

        protected static class mush_mush extends PJProtocolCase {
            public mush_mush() {
                this.tag = "mush_mush";
            }
        }

        protected static class woah extends PJProtocolCase {
            public woah() {
                this.tag = "woah";
            }
        }

        protected static class unharness extends PJProtocolCase {
            public int id;

            public unharness(int id) {
                this.id = id;
                this.tag = "unharness";
            }
        }

        protected static class elves_ready extends PJProtocolCase {
            public elves_ready() {
                this.tag = "elves_ready";
            }
        }

        protected static class greet extends PJProtocolCase {
            public int id;

            public greet(int id) {
                this.id = id;
                this.tag = "greet";
            }
        }

        protected static class consulting extends PJProtocolCase {
            public consulting() {
                this.tag = "consulting";
            }
        }

        protected static class santa_done extends PJProtocolCase {
            public santa_done() {
                this.tag = "santa_done";
            }
        }

        protected static class goodbye extends PJProtocolCase {
            public int id;

            public goodbye(int id) {
                this.id = id;
                this.tag = "goodbye";
            }
        }
    }

    protected static class Message {
    }

    public static void _method$foo$cwLSanta_msg(PJChannel<PJProtocolCase> _pd$out1) {
    }

    public static class _proc$main$arT extends PJProcess {
        protected String[] _pd$args1;

        protected PJChannel<PJProtocolCase> _ld$report1;

        public _proc$main$arT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            _ld$report1 = new PJMany2OneChannel<PJProtocolCase>();
            santatest._method$foo$cwLSanta_msg(_ld$report1);
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new santatest._proc$main$arT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}