import java.util.*;
import processj.runtime.*;
import std.io;


/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'sharedread.pj'.
 * Target class 'sharedread'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas
 * @since 1.2
 *
 */
public class sharedread {
    // Temporary dirty fix for unreachable code due to infinite loop
    public static boolean isTrue() { return true; }

    public static class _proc$reader$I$crI extends PJProcess {
        protected int _pd$id1;
        protected PJOne2ManyChannel<Integer> _pd$in2;

        protected int _ld$v1;

        public _proc$reader$I$crI(int _pd$id1, PJOne2ManyChannel<Integer> _pd$in2) {
            this._pd$id1 = _pd$id1;
            this._pd$in2 = _pd$in2;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                case 2: resume(2); break;
                case 3: resume(3); break;
                default: break;
            }

            while (isTrue()) {
                if (!_pd$in2.claimRead(this)) {
                    this.runLabel = 1;
                    yield();
                }
                label(1);

                if (!_pd$in2.isReadyToRead(this)) {
                    this.runLabel = 2;
                    yield();
                }

                label(2);
                _ld$v1 = _pd$in2.read(this);
                this.runLabel = 3;

                _pd$in2.unclaimRead();

                yield();
                label(3);
                io.println(_pd$id1 + ": " + _ld$v1);
            }
            terminate();
        }
    }

    public static class _proc$writer$cwI extends PJProcess {
        protected PJOne2OneChannel<Integer> _pd$out1;

        protected int _ld$v1;

        public _proc$writer$cwI(PJOne2OneChannel<Integer> _pd$out1) {
            this._pd$out1 = _pd$out1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                default: break;
            }

            _ld$v1 = 0;
            while (isTrue()) {
                _pd$out1.write(this, _ld$v1);
                this.runLabel = 1;
                yield();
                label(1);

                _ld$v1 = _ld$v1 + 1;
            }
            terminate();
        }
    }

    public static class _proc$main$arT extends PJProcess {
        protected String[] _pd$args1;

        protected PJOne2ManyChannel<Integer> _ld$c1;
        protected int _ld$a2;

        public _proc$main$arT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            switch (this.runLabel) {
                case 0: break;
                case 1: resume(1); break;
                default: break;
            }

            _ld$c1 = new PJOne2ManyChannel<Integer>();
            _ld$a2 = 129;
            final PJPar _ld$par1 = new PJPar(4, this);

            (new sharedread._proc$reader$I$crI(1, _ld$c1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new sharedread._proc$reader$I$crI(2, _ld$c1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new sharedread._proc$reader$I$crI(3, _ld$c1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            (new sharedread._proc$writer$cwI(_ld$c1) {
                @Override
                public void finalize() {
                    _ld$par1.decrement();
                }
            }).schedule();

            if (_ld$par1.shouldYield()) {
                this.runLabel = 1;
                yield();
                label(1);
            }

            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new sharedread._proc$main$arT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}