import java.util.*;
import processj.runtime.*;
import std.io;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'SwitchDemo'.
 * Target class 'SwitchDemo'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group
 * @since 1.2
 *
 */
public class SwitchDemo {
    public static class _proc$main$arT extends PJProcess {
        protected String[] _pd$args1;

        protected int _ld$a1;
        protected int _ld$b2;

        public _proc$main$arT(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            _ld$a1 = 4;
            switch(_ld$a1) {
            case 1:
                break;
            case 2:
                break;
            case 4:
                io.println("Hello!1");
                io.println("Hello!2");
                io.println("Hello!3");
                _ld$b2 = 5;
                switch(_ld$b2) {
                case 1:
                    break;
                case 2:
                    break;
                case 5:
                    io.println("in case 5!");
                    break;
                }
                break;
            case 5:
                break;
            default:
                io.println("default case");
                break;
            }
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new SwitchDemo._proc$main$arT(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}