import java.util.*;
import processj.runtime.*;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'test22.pj'.
 * Target class 'test22'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas
 * @since 1.2
 *
 */
public class test22 {
    // Temporary dirty fix for unreachable code due to infinite loop
    public static boolean isTrue() { return true; }

    protected static class P {
        protected static class a extends PJProtocolCase {
            public int b;
            public int c;

            public a(int b, int c) {
                this.b = b;
                this.c = c;
                this.tag = "a";
            }
        }

        protected static class b extends PJProtocolCase {
            public double d;
            public int a;

            public b(double d, int a) {
                this.d = d;
                this.a = a;
                this.tag = "b";
            }
        }

        protected static class c extends PJProtocolCase {
            public R r;

            public c(R r) {
                this.r = r;
                this.tag = "c";
            }
        }
    }

    protected static class A {
        protected static class tag1 extends PJProtocolCase {
            public tag1() {
                this.tag = "tag1";
            }
        }
    }

    protected static class R implements PJRecord {
        public int b;
        public int c;
        public double d;
        public PJProtocolCase p;

        public R(int b, int c, double d, PJProtocolCase p) {
            this.b = b;
            this.c = c;
            this.d = d;
            this.p = p;
        }
    }
}