import java.util.*;
import processj.runtime.*;

/**
 * File generated by the ProcessJ JVM Compiler.
 * Package name 'tests'.
 * Code generation for 'verySimple.pj'.
 * Target class 'verySimple'.
 * Java code version '1.8.0_66'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas
 * @since 1.2
 *
 */
public class verySimple {
    // Temporary dirty fix for unreachable code due to infinite loop
    public static boolean isTrue() { return true; }

    public static class _proc$main1169311 extends PJProcess {
        protected String[] _pd$args1;

        protected PJChannel<Integer> _ld$chanA1;
        protected PJChannel<Integer> _ld$chanB2;
        protected PJChannel<Integer> _ld$chanC3;
        protected PJChannel<Integer> _ld$chanD4;
        protected PJChannel<Integer> _ld$chanE5;
        protected PJChannel<Integer> _ld$chanF6;
        protected PJChannel<Integer> _ld$chanG7;
        protected PJChannel<Integer> _ld$chanH8;
        protected int _ld$p09;
        protected int _ld$p110;
        protected int _ld$p211;
        protected int _ld$p312;
        protected int _ld$p413;
        protected int _ld$p514;
        protected int _ld$p615;
        protected int _ld$p716;

        public _proc$main1169311(String[] _pd$args1) {
            this._pd$args1 = _pd$args1;
        }

        @Override
        public synchronized void run() {
            _ld$chanA1 = new PJOne2OneChannel<Integer>();
            _ld$chanB2 = new PJOne2OneChannel<Integer>();
            _ld$chanC3 = new PJOne2OneChannel<Integer>();
            _ld$chanD4 = new PJOne2OneChannel<Integer>();
            _ld$chanE5 = new PJOne2OneChannel<Integer>();
            _ld$chanF6 = new PJOne2OneChannel<Integer>();
            _ld$chanG7 = new PJOne2OneChannel<Integer>();
            _ld$chanH8 = new PJOne2OneChannel<Integer>();
            terminate();
        }
    }

    public static void main(String[] _pd$args1) {
    	Scheduler scheduler = new Scheduler();
        PJProcess.scheduler = scheduler;
        (new verySimple._proc$main1169311(_pd$args1)).schedule();
        PJProcess.scheduler.start();
    }
}