package utilities;

import java.io.File;
import java.util.Iterator;
import java.util.Stack;

import org.stringtemplate.v4.ST;

/**
 * The class {@link ErrorTracker} is used to track down various
 * types of error messages generated by the ProcessJ compiler
 * at compile-time or run-time.
 * 
 * @author Ben
 * @version 21/10/2018
 * @since 1.2
 */
public enum ErrorTracker {
    
    INSTANCE
    ;
    
    /**
     * Number of errors messages generated by the compiler.
     */
    private int errorCount;
    
    /**
     * List of errors messages.
     */
    private Stack<PJErrorMessage> errorTrace;
    
    /**
     * Input file that contains error/warning messages.
     */
    public String fileName = "";
    
    /**
     * Namespace for input file.
     */
    public String packageName = "";
    
    ErrorTracker() {
        errorCount = 0;
        errorTrace = new Stack<>();
    }
    
    public void add(PJErrorMessage errorMessage) {
        ErrorSeverity severity = errorMessage.getError().getErrorSeverity();
        switch (severity) {
        case INFO:
        case WARNING:
            break;
        case ERROR:
            ++errorCount;
            break;
        }
        errorTrace.push(errorMessage);
    }
    
    public void printAndContinue(PJErrorMessage errorMessage) {
        ST msg = errorMessage.getST();
        System.out.println(msg.render());
        add(errorMessage);
    }
    
    public void dontPrintJustContinue(PJErrorMessage errorMessage) {
        add(errorMessage);
    }
    
    public void printAndStop(PJErrorMessage errorMessage) {
        add(errorMessage);
        ST msg = errorMessage.getST();
        System.out.println(msg.render());
        System.exit(0);
    }
    
    public int getErrorCount() {
        return errorCount;
    }
    
    public Stack<PJErrorMessage> getTrace() {
        return errorTrace;
    }
    
    public void printTrace(String source) {
        System.out.println("=============== E R R O R   R E P O R T ===============");
        System.out.println(String.format("%d error(s) in %s", errorCount, source));
        Iterator<PJErrorMessage> it = errorTrace.iterator();
        while (it.hasNext()) {
            System.out.println(it.next().render());
            if (it.hasNext())
                System.out.println("+------------------------------------------------------");
        }
    }
    
    public void setPackageName(String name) {
        // First strip the `.pj' part
        String str = name.replaceAll("\\.pj$", "");
        // Now remove the absolute path
        String absPath = new File("").getAbsolutePath() + "/";
        str = str.replaceAll(absPath, "");
        // replace all `/' with .
        str = str.replaceAll("/", "\\.");
        packageName = str;
    }
    
    public void setFileName(String name) {
        // remove all double `//:'
        String str = name.replaceAll("//","/");
        // Now remove the absolute path
        String absPath = new File("").getAbsolutePath() + "/";
        str = str.replaceAll(absPath,"");
        fileName = str;
    }
}
