package utilities;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Ben Cisneros
 * @version 21/10/2018
 * @since 1.2
 */
public enum StackErrorMessage {
    
    INSTANCE
    ;
    
    /**
     * Number of errors messages generated by the compiler.
     */
    private int errorCount;
    
    /**
     * List of errors messages.
     */
    private List<BaseErrorMessage> trace;
    
    StackErrorMessage() {
        errorCount = 0;
        trace = new ArrayList<>();
    }
}
